// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkitnfvgxkozfqfpjrcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhraXRuZnZneGtvemZxZnBqcmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjY1NjMsImV4cCI6MjA2Nzk0MjU2M30.yyN_AlhORpSj9VFrOH5zNMRiZeHId72jlDvCwPNm4_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});